### ISSUE TITLE
TableView InitialData is spelled incorrectly

### ISSUE THREAD

**Issue by 0xLeif** [0xLet/SwiftUIKit#185]
https://github.com/0xLet/SwiftUIKit/blob/aab49fc782010c5ae5144c7fd2e85af78d367bb8/Sources/SwiftUIKit/Views/TableView.swift#L67

Expected: `initialData`

Actual: `initalData`

**Comment by AC40** [comment]
Does this still need to be fixed? I am looking for a good first issue, and this seems good. However the message `added a commit that referenced this issue on 2 Jun` and `resolves #185` confuses me.
If it still needs to be fixed, I would like to do that.

**Comment by 0xLeif** [comment]
I apologize as this has been resolved, but has not been merged into develop. I will close this now.

**Comment by 0xLeif** [comment]
@AC40 I will try to create more issues for this project that you could potentially work!

**Comment by AC40** [comment]
Okay, thanks for the explanation. I'll keep my eyes open for future Issues.
